export const path = {
  home: "",
  login: "/login",
  logout: "/logout",
  register: "/register",
  productDetail: "/products/:slug",
  productCategoryBrand: "/products/:categorySlug/brand/:brandSlug",
  cart: "/cart",
  cartStepTwo: "/cart/step-two",
  cartStepThree: "/cart/step-three",
  cartStepFour: "/cart/step-four",
  notFound: "/not-found",
  account: "/account",
  address: "/account/address",
  orderHistory: "/account/order-history",
  orderHistoryDetail: "/account/order-history/:id",
  viewed: "/account/viewed",
  contact: "/contact",
  paymentInstruction: "/payment-instruction",
  // Admin paths
  homeAdmin: "/admin",
  productManagement: "products",
  orderManagement: "orders",
  report: "reports",
  userManagement: "users",
  loginAdmin: "/loginAdmin",
};