export const path = {
  home: "/",
  login: "/login",
  logout: "/logout",
  register: "/register",
  productDetail: "/products/:slug",
  cart: "/cart",
  cartStepTwo: "/cart/step-two",
  cartStepThree: "/cart/step-three",
  cartStepFour: "/cart/step-four",
  notFound: "/not-found",
  account: "/account",
  address: "/account/address",
  orderHistory: "/account/order-history",
};
